### ISSUE TITLE
npm package informations and screencast example

### ISSUE THREAD

**Issue by ggirodda** [eweap/strapi-plugin-instagram#1]
Hi, thank you for the plugin, I'm starting to use it. Could you please publish your last version on npm ? Because the readme isn't currently visible on npm, I think it's because the last published version didn't yet contain the readme file. Can you also put in package.json the `repository` and `homepage` attributes ? The link to your github repository will be visible on the npm page of the package.
I'd also like to know what kind of screencast did you put on facebook app. This information is required when creating app that uses `instagram_graph_user_profile` and `instagram_graph_user_media`

Thank you in advance

**Comment by eweap** [comment]
Hi @ggirodda  !
You are right, I've rushed the npm publication and miss some properties. I'll fix the package by the end of this week.

At this time, I still haven't submitted my app to Facebook. My FB application is in test mode with a test user.
This is sufficient even in production, you just have to add the account that will be connected through this plugin to the testers of the Facebook application.

If you attempt to submit your FB application for this plugin, I will be interested in your feedback.

**Comment by ggirodda** [comment]
Hi, thank you for your answer.

It's the first time I use the facebook api for instagram, I didn't know that it'll work even in test mode. I think I'll do the same if no restrictions are applied. If in the future I'll submit the app to FB, I'll maybe have to lie :-) I don't think that they'll approve the plugin usage, because there'll be no useful users data to collect for them

**Comment by eweap** [comment]
@ggirodda I have published to `0.1.4` on npm

Now the package have a `README.md`, `CHANGELOG.md`, repository version tags and some documentation to get started with the plugin.
